export const GET_ADDRESS_COLLECTION = "GET_ADDRESS_COLLECTION"
export const POST_COLLECTION_FORM = "POST_COLLECTION_FORM";
export const POST_COLLECTION_PREREQUISITE_FORM = "POST_COLLECTION_PREREQUISITE_FORM";
export const POST_NFT_DROP_FORM = "POST_NFT_DROP_FORM";
